---
twitter: https://twitter.com/motivated_it
github: https://github.com/Amoenus
linkedin: https://www.linkedin.com/in/romanspokrovskis/
youtube: https://www.youtube.com/watch?v=iPDCmbaEF0Y
devto: https://dev.to/amoenus
nuget: https://www.nuget.org/profiles/Amoenus
dribbble: ''
instagram: ''
facebook: ''
medium: https://medium.com/@Amoenus
patreon: ''
paypal: https://paypal.me/Amoenus
unsplash: ''
